NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8066-ca-storage.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8066-ca-storage.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8066-ca-storage.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8066-ca-storage.pem
    OrganizationalUnitIdentifier: orderer
